#!/usr/bin/env bash
echo "This is the git rm command."

# The command's name
echo -e 'git add'

# the command's description
echo "The git add command is executed when you are ready to create a snapshot out of the changes you’ve made. The snapshot goes to the staging area before being committed. Git add is the step before git commit. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git test argument1 argument2"
echo -e "\targument1: description of argument 1"
echo -e "\targument2: description of argument 2"
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
