#!/usr/bin/env bash
echo "This is the git checkout command."

# The command's name
echo -e 'git checkout'

# the command's description
echo "The checkout command is used to switch between branches and can also be used to restore delete files. Combined with flags the checkout command can perform multiple tasks such as create or merge branches with a single command.. "

echo "------------"

# the command's syntax
echo "Syntax:"
echo "git checkout [-b |  -t |-track] <branch>"
echo -e "\t-b: The git pull command in conjuction with a –b flag causes a new branch to be created as if git branch were called and then checked out. In this case, use the –track or –no-track options.”
echo -e "\t-t | -track: When creating a new branch, the track option configures git to use the start point branch as the upstream repository.”
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
