#!/usr/bin/env bash
echo "This is the git pull command."

# The command's name
echo -e 'git pull'

# the command's description
echo "The git pull command will fetch from the remote repository and integrate it into the local branch. This command is a compound or short-hand command. When you issue a git pull command, git first runs a git fetch, followed by a git merge, merging the FETCH_HEAD into the local branch. You can modify the actions using various flags, such as whether to commit or not, or changing the merge to a rebase."

echo "------------"

# the command's syntax

echo "Syntax:"
echo "git pull [-all |  -commit] <repository>"
echo -e "\t-all: The git pull command in conjuction with a –all flag will fetch all the remotes associated with that local repository.”
echo -e "\t-commit: This flag combines the git pull with the git commit command..”

#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
