#!/usr/bin/env bash
echo "This is the git reset command."

# The command's name
echo -e 'git reset'

# the command's description
echo "Used to reset the HEAD to a earlier, specified version. A reset is often used to 'undo' a git add. For example, a git reset <filename> is the opposite of git add <filename>. A reset, depending on the [<mode>] provided can change the working tree, the index or both."

echo "------------"

# the command's syntax
echo “Syntax”
echo "git reset [--soft | --hard] <HEAD>"
echo -e "\t-soft: A soft reset in git is appropriate when you committed something that was incomplete or if you misspelled your commit message. In this case you would run a git reset –soft, make the edit, and recommit.”
echo -e "\t-hard: A hard reset will undo a commit but this should NEVER be done if someone has already merged the changes into their repository.”
#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
