#!/usr/bin/env bash
echo "This is the git status command "

# The command's name
echo -e 'git status'

# the command's description
echo "Shows the status of the git working tree. When this command is entered in a local repository, it will show the status of the working tree. Any files that differ from the current HEAD will be diplayed as a path to that file. This includes files or directories that have been added, deleted, or modified. A number of flags are available to help fine-tune the output."

echo "------------"

# the command's syntax

echo "Syntax:"
echo "git status [-long |  -s | -v ]"
echo -e "\t-long: This is the default behavior. “
echo -e "\t-s: This prints the output in a PATH1 à PATH2 format.”
echo -e "\t-v: This shows the files that will be changed and also the textual changes to the file.”

#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "git test"
echo description here

# example 2
echo "git test something"
echo description here


exit 0
