#!/usr/bin/env bash
echo "This is the grep command."

# The command's name
echo -e 'grep'

# the command's description
echo "The command grep is used to search text for supplied patterns. This powerful tool is one of the most used commands and is often combined with other commands using the '|' (pipe) operator. This command is extremely flexible due in part to the large amount of flags available to it."

echo "------------"

# the command's syntax

echo "Syntax:"
echo "grep [ -f | -g ] [PATTERN]"
echo -e "\t-f: Using grep with a –f flag followed by a pattern tells grep to interpret the pattern as a list of fixed strings separated by new lines.”
echo -e "\t-g: Using grep with a –g flag followed by a pattern tells grep to interpret the pattern as a REGEX expression.”

#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
