#!/usr/bin/env bash
echo "This is a test command."

# The command's name
echo -e 'test'

# the command's description
echo "description here"

echo "------------"

# the command's syntax
echo "Syntax:"
echo "mv [ --suffix, -S | -u ]"
echo -e "\t--suffix, -S: Creates a backup of the destination before overwriting it. Used when you want to replace file1 with file2 but keep a copy of file2. This flag adds the supplied suffix to the original filename."
echo -e "\t-u: Moves only the files that do not exist in the destination directory. Useful when moving files using wildcards."
#   ...      etc

echo "------------"

# the command's usage examples

# example 1
echo "mv –S=$ /path/to/source /path/to/destination"
echo "This replaces the usual ~ in the file path to the $ character. ”
 
# example 2
echo "mv -u /path/to/source /path/to/destination”
echo "This moves the file only when the SOURCE file is newer than the destination.”



exit 0
