#!/usr/bin/env bash
echo "This is the rmdir command."

# The command's name
echo -e 'rmdir'

# the command's description
echo "The rmdir command is used to remove empty directories. This command will fail if the directory contains any files. If the directory is not empty use the rm command (with appropriate flags) to remove any files or sub-directories."

echo "------------"

# the command's syntax

echo "Syntax:"
echo "rmdir [ -p | -v ] [DIRECTORY]"
echo -e "\t-p: Using rmdir with the –p flag tells bash to remove all of the directories in the path including the parent.”
echo -e "\t-v: Using rmdir with the –v flag will ensure a diagnostic output is displayed for every directory affected by the rmdir command.”

#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
