#!/usr/bin/env bash
echo "This is the tar command."

# The command's name
echo -e 'tar'

# the command's description
echo "The tar command is used to archive files into a single file as well as reverse the process. 'tar' is often used to group files together for backup and comes with a compression algorithim that can reduce the overall size of the resulting tar file. This is also important when sending files over the internet."

echo "------------"

# the command's syntax

echo "Syntax:"
echo "tar [ -c | -d | -r] [tar name] [file1 file 2]"
echo -e "\t-c: Using tar with the –c flag will create a new archive named [tar name] that contains the files [file1 file2].”
echo -e "\t-d: Using tar with the –d flag will find the differences between [tar name] and the files [file1 file2].”
echo -e "\t-r: Using tar with the –r flag will append the files [file1 file2] to the  archive named [tar name].”

#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "$ tar xfz file.tar.gz"
echo "Extract the gzip compressed file.tar.gz in the current directory."
echo
# example 2
echo "$ tar -cfz file.tar.gz foo/"
echo "Archive recursively the directory \"foo\" in file.tar.gz with gzip compression."


exit 0
