#!/usr/bin/env bash
echo "This is the touch command."

# The command's name
echo -e 'touch'

# the command's description
echo "The touch command is an easy way to create new, empty files. Touch is also used to changed the timestamps on existing files, without modifying the contents. The file's timestamp would change to the date and time the file was 'touched'."

echo "------------"

# the command's syntax

echo "Syntax:"
echo "touch [ -c | -a ] file_name1 filename2"
echo -e "\t-c: Using touch without any flags will create a file if it does not exist already. Adding the –c flag will prevent the creation of new files.”
echo -e "\t-a: This flag allows a user to change the access time of the file to the current time.”

#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
