#!/usr/bin/env bash
echo "This is the whoami command."

# The command's name
echo -e 'whoami'

# the command's description
echo "The whoami command prints the name of the user logged into the current shell. Often used to determine who the current user is."

echo "------------"

# the command's syntax

echo "Syntax:"
echo "whoami”
echo -e "\t- There are no flags associated with this command.”

#   ...      etc

echo "------------"

# the command's usage examples
# example 1
echo "test"
echo description here

# example 2
echo "test something"
echo description here


exit 0
